# Form implementation generated from reading ui file 'd:\Estudos\Python\PyQt\Aula 12 (Barra de Progresso)\aula12.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(393, 468)
        MainWindow.setStyleSheet("background-color: rgb(0, 85, 255);color:#ffffff;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(50, 160, 291, 20))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("QProgressBar{background-color:rgb(0, 65, 197);text-align:center;color:#000000;border-radius:10px;}QProgressBar::chunk{background-color:rgb(85, 255, 0);border-radius:10px;}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 230, 120, 40))
        self.pushButton.setStyleSheet("QPushButton{background-color:#FFFFFF;color:#000000;border-radius:20px;}QPushButton:hover{background-color:#c4c4c4;}QPushButton:pressed{background-color:#999999;}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(201, 230, 120, 40))
        self.pushButton_2.setStyleSheet("QPushButton{background-color:#FFFFFF;color:#000000;border-radius:20px;}QPushButton:hover{background-color:#c4c4c4;}QPushButton:pressed{background-color:#999999;}")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 393, 21))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Aumentar"))
        self.pushButton_2.setText(_translate("MainWindow", "Zerar"))
